name: Python application

on: [push]

jobs:
  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.6
    - name: Install pip
      run: |
        python -m pip install --upgrade pip
    - name: Install poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Run pre-commit
      run: |
        poetry run pre-commit run --all-files
    - name: Test with pytest
      run: |
        poetry run pytest
